### ISSUE TITLE
👾 [BUG] FBX Models create a Error if the Importer get Changed! (Create a Error in Content Editor)

### ISSUE THREAD

**Issue by MrScautHD** [LiruJ/MonoGame-Skinned-Mesh-Importer#2]
**Describe the bug**
Hello!
I try to set my FBX Model to the SkinnedMesh Importer and it create a Error by Building.
![grafik](https://user-images.githubusercontent.com/65916181/204125116-8a033b0e-c48e-4d54-bab7-60900c7118b8.png)

**Desktop (please complete the following information):**
 - Windows: 11
 - Version: 1.0.2

Model:
https://cdn.discordapp.com/attachments/1045595259389874236/1046335668277747835/street_light.fbx

Texture:
![street_light](https://user-images.githubusercontent.com/65916181/204125175-ab6ae1e0-f166-498f-97dd-d6ae7347a020.png)

**Comment by MrScautHD** [comment]
Pls Update to 5.2,5!
https://github.com/assimp/assimp/releases/tag/v5.2.5

**Comment by LiruJ** [comment]
Added a check to ensure the mesh has bones when it is imported.

**Comment by MrScautHD** [comment]
ah ok thx!
